### ISSUE TITLE
Searching for a new active maintainer

### ISSUE THREAD

**Issue by antitoxic** [web-napopa/node-reversable-router#6]
Due to new NGO project to do with Civic Hacking in my locality (Bulgaria) I am not able to actively invest time in **node-reversable-router**. 

Which has a typo in its name. I know - silly.

I'm happy to add anyone to the project as active maintainer and to credit all of this in the docs. I am happy to transfer the project to another owner as long as it lives.

I am now tagging the people that have been more active in the issue tracker:
@pocesar
@langri-sha
@mrmonkington
@nazomikan 

Anyone else is welcomed to raise their hand.

**Comment by eliaslfox** [comment]
Seeing as this is resolved, you should remove the link from the readme.

**Comment by antitoxic** [comment]
@alubbe can you do a pull request for changes in the readme as you see fit? So that people know that your fork is the active one?

**Comment by antitoxic** [comment]
@eliaslfox done. Thank you for raising the problem.
